# used by the docker image
# used when stack is invoked with --system-ghc
packages: []
extra-deps:
  # check https://hackage.haskell.org/package/<name>
  - base-4.10.1.0
  - scotty-0.11.0
  - shakespeare-2.0.14
  - network-uri-2.6.1.0
  - cassava-0.5.1.0
  - text-short-0.1.1
flags:
  cassava:
    bytestring--LT-0_10_4: false
resolver: lts-9.5
